name: bench
version: 0.0.2-dev
description: a micro benchmark library for dart
author: Ross Smith
homepage: https://github.com/rmsmith/bench
dependencies:
  logging:
    sdk: logging
  unittest:
    sdk: unittest